AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: OrderRequestHandler
Resources:
  ReceiverFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/aws-content-detector.jar
      Handler: ming.test.OrderRequestHandler::handleRequest
      Runtime: java8
      Description: Java function
      MemorySize: 128
      Timeout: 20
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      Tracing: Active

      Events:
        SubmitOrderEvent:
          Type: Api
          Properties:
            Path: /
            Method: POST

      Environment:
        Variables:
          DB_URL:
          DB_USERNAME:
          DB_PASSWORD:

  ContentDetector:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/aws-content-detector.jar
      Handler: ming.test.ContentDetectorHandler::handleRequest
      Runtime: java8
      Description: Java function
      MemorySize: 128
      Timeout: 20
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      Tracing: Active

      Environment:
        Variables:
          DB_URL:
          DB_USERNAME:
          DB_PASSWORD:
          DETECT_STRATEGY:

      Events:
        SnsEvent:
          Type: SNS
          Properties:
            Topic: