AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: OrderRequestHandler
Resources:
  ReceiverFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/aws-content-detector.jar
      Handler: ming.test.OrderRequestHandler::handleRequest
      Runtime: java8
      Description: Java function
      MemorySize: 128
      Timeout: 5
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      Tracing: Active

      Events:
        SubmitOrderEvent:
          Type: Api
          Properties:
            Path: /
            Method: POST

      Environment:
        Variables:
          DB_URL: jdbc:postgresql://<host>:<port>/<database:postgres>
          DB_USERNAME: <db_username>
          DB_PASSWORD: <password>

      VpcConfig:
        SecurityGroupIds:
          - sg-XXXXXXXX
        SubnetIds:
          - subnet-XXXXXXXX
          - subnet-XXXXXXXX
          - subnet-XXXXXXXX

  HelloContentDetector:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/aws-content-detector.jar
      Handler: ming.test.ContentProducerHandler::handleRequest
      Runtime: java8
      Description: Java function
      MemorySize: 128
      Timeout: 5
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      Tracing: Active

      Environment:
        Variables:
          DB_URL: jdbc:postgresql://<host>:<port>/<database:postgres>
          DB_USERNAME: <db_username>
          DB_PASSWORD: <password>
          DETECT_STRATEGY: ming.test.detector.HelloDetector

      VpcConfig:
        SecurityGroupIds:
          - sg-XXXXXXXX
        SubnetIds:
          - subnet-XXXXXXXX
          - subnet-XXXXXXXX
          - subnet-XXXXXXXX
          
      Events:
        SnsEvent:
          Type: SNS
          Properties:
            Topic: <sns-topic-arn>